# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `io-stream` gem.
# Please instead update this file by running `bin/tapioca gem io-stream`.


# StringIO extensions for buffering support.
class StringIO
  include ::Enumerable
end
