# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-cobertura` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-cobertura`.


# source://simplecov-cobertura//lib/simplecov-cobertura/version.rb#1
module SimpleCov; end

# source://simplecov-cobertura//lib/simplecov-cobertura/version.rb#2
module SimpleCov::Formatter; end

# source://simplecov-cobertura//lib/simplecov-cobertura/version.rb#3
class SimpleCov::Formatter::CoberturaFormatter
  # @return [CoberturaFormatter] a new instance of CoberturaFormatter
  #
  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#15
  def initialize(result_file_name: T.unsafe(nil)); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#19
  def format(result); end

  private

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#151
  def coverage_output(result); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#166
  def extract_rate(percent); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#170
  def project_root; end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#162
  def resolve_filename(filename); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#36
  def result_to_xml(result); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#134
  def set_branch_attributes(line, file_line, branched_lines, branched_lines_covered); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#115
  def set_class_attributes(class_, file); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#86
  def set_coverage_attributes(coverage, result); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#129
  def set_line_attributes(line, file_line); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#103
  def set_package_attributes(package, name, result); end

  # source://simplecov-cobertura//lib/simplecov-cobertura.rb#144
  def set_xml_head(lines = T.unsafe(nil)); end
end

# source://simplecov-cobertura//lib/simplecov-cobertura.rb#13
SimpleCov::Formatter::CoberturaFormatter::DTD_URL = T.let(T.unsafe(nil), String)

# source://simplecov-cobertura//lib/simplecov-cobertura.rb#12
SimpleCov::Formatter::CoberturaFormatter::RESULT_FILE_NAME = T.let(T.unsafe(nil), String)

# source://simplecov-cobertura//lib/simplecov-cobertura/version.rb#4
SimpleCov::Formatter::CoberturaFormatter::VERSION = T.let(T.unsafe(nil), String)
